services:
    similartopics.manager:
        class: vse\similartopics\core\similar_topics
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @template
            - @user
            - @content.visibility
            - %core.root_path%
            - %core.php_ext%
