services:
    vse.similartopics.manager:
        class: vse\similartopics\core\similar_topics
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @pagination
            - @request
            - @template
            - @user
            - @content.visibility
            - %core.root_path%
            - %core.php_ext%
    vse.similartopics.listener:
        class: vse\similartopics\event\listener
        tags:
            - { name: event.listener }
