services:
    similartopics.manager:
        class: phpbb_ext_vse_similartopics_core_similar_topics
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
